# Generated by Django 3.0.8 on 2021-07-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='restaurant',
        ),
    ]
