# Generated by Django 3.0.8 on 2021-08-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_pizza_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='state',
            field=models.CharField(choices=[('RAW', 'Raw'), ('COOKING', 'Cooking'), ('DONE', 'Done')], default='RAW', max_length=7),
        ),
    ]
