# Generated by Django 3.0.8 on 2021-08-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_auto_20210802_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='state',
            field=models.CharField(default='RAW', max_length=10),
        ),
    ]
